Areas/Manager/Controllers/DMHocPhiController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TestDA.DB;
using TestDA.Areas.Manager.Models.EntityManager;
using TestDA.Areas.Manager.Models.ViewModel;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Web.UI.WebControls;
using TestDA.Security;

namespace TestDA.Areas.Manager.Controllers
{
    public class DMHocPhiController : BaseController
    {
        // GET: Manager/DMHocPhi
        [AuthorizeRoles("Admin", "HieuTruong","VanThu")]
        public ActionResult Index(string namHoc, string loaiApDung)
        {
            //lấy toàn bộ định mức học phí trong cơ sở dữ liệu
            DMHocPhiManager DMHP = new DMHocPhiManager();
            DMHocPhiData data = new DMHocPhiData();
            data.danhSachDMHocPhi = DMHP.DanhSachDMHocPhi(namHoc, loaiApDung);
            setYears();
            return View(data);
        }
        public void setYears(string selectedID = null)
        {
            List<SelectListItem> Years = new List<SelectListItem>();
            int now = DateTime.Now.Year;
            for (int i = now; i >2010;i-- )
            {
                Years.Add(new SelectListItem()
                 {
                     Text = ((i - 1) + "-" + i).ToString(),
                     Value = ((i - 1) + "-" + i).ToString(),
                     Selected = false
                 });
            }
            ViewBag.namHoc = new SelectList(Years, "Value", "Text", selectedID);
        }
        public void setLoaiChiPhi(int? selectedId = null)
        {
            //lấy danh sách loại chi phí
            LoaiChiPhiManager LCP = new LoaiChiPhiManager();
            ViewBag.maLoaiChiPhi = new SelectList(LCP.ListLoaiChiPhi(), "maLoaiChiPhi", "tenLoai", selectedId);
        }
        public void setNhomLop(int? selectedId = null)
        {
            //lấy danh sách nhóm lớp
            NhomLopManager NLM = new NhomLopManager();
            ViewBag.maNhomLop = new SelectList(NLM.ListNhomLop(), "maNhomLop", "tenNhomLop", selectedId);
        }
        public void setLoaiApDung(string selectedID = null)
        {
            List<SelectListItem> SetValue = new List<SelectListItem>();
            SetValue.Add(new SelectListItem()
            {
                Text = "Đóng theo tháng",
                Value = "1",
                Selected = false
            });
            SetValue.Add(new SelectListItem()
            {
                Text = "Đóng theo năm",
                Value = "2",
                Selected = false
            });
            ViewBag.loaiApDung = new SelectList(SetValue, "Value", "Text", selectedID);
        }
        //thực hiện chức năng thêm, sửa bản ghi
        public ActionResult ChucNang()
        {
            string type = Request.QueryString["type"].ToString();//lấy thuộc tính type trong đường dẫn
            if (type == "Insert")
            {
                ViewBag.ChucNang = "Thêm mới định mức học phí";

                setLoaiChiPhi();
                setYears();
                setLoaiApDung();

                return View();
            }
            else
            {
                ViewBag.ChucNang = "Chỉnh sửa thông tin định mức phí";

                string maDMHP = Request.QueryString["maDMHP"].ToString();
                int id = int.Parse(maDMHP);

                DMHocPhiManager DPM = new DMHocPhiManager();

                DMHocPhiData data = DPM.LayChiTiet(id);

                setLoaiChiPhi(data.maLoaiChiPhi);
                setYears(data.namHoc);
                setLoaiApDung(data.loaiApDung);

                return View(data);

            }
        }
        //thực hiện chức năng thêm, sửa bản ghi
        [HttpPost]
        public ActionResult ChucNang(DMHocPhiData obj)
        {
            string type = Request.QueryString["type"].ToString();//lấy thuộc tính type trong đường dẫn

            if (type == "Insert")
            {
                if (ModelState.IsValid)//trả về false
                {
                    DMHocPhiManager DPM = new DMHocPhiManager();
                    DPM.ThemMoiDMHP(obj);
                    TempData["Success"] = "Thêm mới thành công";
                    return RedirectToAction("Index", "DMHocPhi");
                }

                setLoaiChiPhi(obj.maLoaiChiPhi);
                setYears(obj.namHoc);
                setLoaiApDung(obj.loaiApDung);

                return View(obj);
            }
            else
            {
                if (ModelState.IsValid)
                {
                    DMHocPhiManager DPM = new DMHocPhiManager();
                    DPM.SuaDMHocPhi(obj);
                    TempData["Success"] = "Chỉnh sửa thành công";
                    return RedirectToAction("Index", "DMHocPhi");
                }

                setLoaiChiPhi(obj.maLoaiChiPhi);
                setYears(obj.namHoc);
                setLoaiApDung(obj.loaiApDung);

                return View(obj);
            }
        }  //kết thúc chức năng thêm , sửa bản ghi 
        //sửa thông tin định mức học phí
        //public ActionResult SuaDMHP()
        //{
        //    DMHocPhiManager DPM = new DMHocPhiManager();
        //    string maDMHP = Request.QueryString["maDMHP"].ToString();
        //    int id = int.Parse(maDMHP);
        //    DMHocPhiData data = DPM.LayChiTietDMHP(id);
        //    setLoaiChiPhi(data.maLoaiChiPhi);
        //    setNhomLop(data.maNhomLop);
        //    return View(data);
        //}
        //[HttpPost]
        //public ActionResult SuaDMHP(DMHocPhiData obj)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        DMHocPhiManager DPM = new DMHocPhiManager();
        //        DPM.SuaDMHocPhi(obj);
        //        TempData["Success"] = "Chỉnh sửa thành công";
        //        return RedirectToAction("Index", "DMHocPhi");
        //    }

        //    setLoaiChiPhi(obj.maLoaiChiPhi);
        //    setNhomLop(obj.maNhomLop);

        //    return View(obj);
        //}
        //Xóa danh sách bản ghi đã chọn
        //public ActionResult XoaDMHP(int[] dmIDs)
        //{
        //    using (DoAnTotNghiepEntities db = new DoAnTotNghiepEntities())
        //    {
        //        foreach (int maDM in dmIDs)
        //        {
        //            tbl_dmhocphi obj = db.tbl_dmhocphi.Find(maDM);
        //            db.tbl_dmhocphi.Remove(obj);
        //        }
        //        db.SaveChanges();
        //        return Json("Xóa thành công những bản ghi được chọn!");
        //    }
        //}

        //Xóa bỏ một bản ghi
        public ActionResult XoaDMHocPhi(int maDMHP)
        {
            DMHocPhiManager LM = new DMHocPhiManager();
            int kq = (int)LM.XoaDMHP(maDMHP);
            return Json(kq);
        }//kết thúc xóa bỏ bản ghi
    }
}

Areas/Manager/Controllers/NhomLopController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TestDA.DB;
using TestDA.Areas.Manager.Models.EntityManager;
using TestDA.Areas.Manager.Models.ViewModel;
using System.ComponentModel.DataAnnotations;
using System.Data;
using TestDA.Security;

namespace TestDA.Areas.Manager.Controllers
{
    public class NhomLopController : BaseController
    {
        // GET: Manager/NhomLop
         [AuthorizeRoles("Admin", "HieuTruong", "VanThu")]
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult NhomLopPartial(string tukhoa)
        {
            NhomLopManager nhomlop = new NhomLopManager();
            NhomLopData data = new NhomLopData();
            if (!String.IsNullOrEmpty(tukhoa))
            {
                tukhoa = tukhoa.Trim();
            }
            data.danhSachNhomLop = nhomlop.LayDSNhomLop(tukhoa);
            ViewBag.TuKhoaTK = tukhoa;

            return PartialView(data);
        }
        //tạo partial view hiển thị danh sách lớp thep nhóm lớp
        public ActionResult DSNhomLopPartial()
        {
            NhomLopManager nhomlop = new NhomLopManager();
            NhomLopData data = new NhomLopData();
            data.danhSachNhomLop = nhomlop.ListNhomLop();

            return PartialView(data);
        }
        //Thêm mới một danh mục 
        [HttpPost]
        public ActionResult ThemNhomLop(NhomLopData obj)
        {
            if (ModelState.IsValid)
            {
                NhomLopManager nhomlop = new NhomLopManager();
                nhomlop.ThemMoiNhomLop(obj);
                return Json("1");
            }
            var errorList = ModelState.ToDictionary(
            kvp => kvp.Key,
            kvp => kvp.Value.Errors.Select(e => e.ErrorMessage).ToArray()
        );
            return Json(errorList);

        }
        //Sửa thông tin một danh mục bản ghi
        public ActionResult SuaNhomLop(int maNhomLop, string tenNhomLop, string ghiChu)
        {
            if (ModelState.IsValid)
            {
                NhomLopManager nhomlop = new NhomLopManager();
                nhomlop.SuaNhomLop(maNhomLop, tenNhomLop, ghiChu);
                return Json("Sửa thông tin bản ghi thành công");
            }
            NhomLopData obj = new NhomLopData();
            obj.tenNhomLop = tenNhomLop;
            obj.ghiChu = ghiChu;
            return View(obj);

        }
        //Xóa bỏ một danh mục
        public ActionResult XoaNhomLop(int maNhomLop)
        {
            NhomLopManager nhomlop = new NhomLopManager();
            int kq = (int)nhomlop.XoaNhomLop(maNhomLop);
            return Json(kq);
        }//kết thúc xóa bỏ một danh mục loại món ăn
    }
}

Areas/Manager/Views/DMHocPhi/ChucNang.cshtml
@model TestDA.Areas.Manager.Models.ViewModel.DMHocPhiData

@{
    ViewBag.Title = "ChucNang";
    Layout = "~/Areas/Manager/Views/Shared/_AdminPartial.cshtml";
}

<section class="content-header">
    <h1>
        <i class="fa fa-building-o"></i>
        Định mức học phí
        <small></small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Trang chủ</a></li>
        <li class="active">Định mức học phí</li>
    </ol>
</section>
<!-- Main content -->
<section class="content">
    <div class="container body-content ">
        <h3>@ViewBag.ChucNang </h3>
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()
            <div class=" form-horizontal">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.maLoaiChiPhi, htmlAttributes: new { @class = "col-sm-2" })
                    <div class="col-sm-5">
                        @Html.DropDownListFor(model => model.maLoaiChiPhi, null, "--Chọn loại chi phí-- ", new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.maLoaiChiPhi, null, new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.soTien, htmlAttributes: new { @class = "col-sm-2" })
                    <div class="col-sm-4">
                        @Html.TextBoxFor(model => model.soTien, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.soTien, null, new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.ngayApDung, htmlAttributes: new { @class = " col-sm-2" })
                    <div class="col-sm-4">
                        @Html.TextBoxFor(model => model.ngayApDung, "{0:yyyy-MM-dd}", new { @class = "form-control", @type = "date" })
                        @Html.ValidationMessageFor(model => model.ngayApDung, null, new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.namHoc, htmlAttributes: new { @class = "col-sm-2" })
                    <div class="col-sm-3">
                        @Html.DropDownListFor(model => model.namHoc, null, "--Chọn năm học-- ", new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.namHoc, null, new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.loaiApDung, htmlAttributes: new { @class = "col-sm-2" })
                    <div class="col-sm-3">
                        @Html.DropDownListFor(model => model.loaiApDung, null, "--Chọn hình thức áp dụng-- ", new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.loaiApDung, null, new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.ghiChu, htmlAttributes: new { @class = "col-sm-2" })
                    <div class="col-sm-7">
                        @Html.TextAreaFor(model => model.ghiChu, new { @class = "form-control", @rows = 5 })
                        @Html.ValidationMessageFor(model => model.ghiChu, null, new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.ActionLink("<< Quay lại danh sách", "Index", "DMHocPhi")
                    <div class="col-sm-offset-2 col-sm-10">
                        <button type="reset" class="btn btn-primary" style="margin-right:10px;"><i class="fa fa-refresh"></i>Làm mới</button><button type="submit" value="Lưu thông tin" class="btn btn-primary"><i class="fa fa-save"></i>Lưu thông tin</button>
                    </div>
                </div>
            </div>
        }
    </div>
</section>

Areas/Manager/Views/DMHocPhi/HPTheoNhomLop.cshtml
@model TestDA.Areas.Manager.Models.ViewModel.DMHocPhiData

@{
    ViewBag.Title = "HPTheoNhomLop";
    Layout = "~/Areas/Manager/Views/Shared/_AdminPartial.cshtml";
}

<section class="content-header">
    <h1>
        <i class="fa fa-building-o"></i>
        Định mức học phí
        <small></small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Trang chủ</a></li>
        <li class="active">Định mức học phí</li>
    </ol>
</section>
<!-- Main content -->
<section class="content">
    <div class="container body-content ">
        <h3>Định mức học phí theo nhóm lớp</h3>
        <div class="row">
            <div class="row">
                <div class="form-group col-md-6">
                    <label class="col-sm-5">Nhóm lớp:</label>
                    <div class="col-sm-7">
                        @ViewBag.tenNhomLop
                    </div>
                </div>
                <div class="form-group col-md-6">
                    <a href="/Manager/DMHocPhi/ChucNang?type=Insert&&maNhomLop=@ViewBag.maNhomLop" class="btn btn-primary hidden-xs pull-right" style="margin-right:15px;"><i class="glyphicon glyphicon-plus"></i>Thêm mới loại phí cần đóng</a>
                </div>
                
            </div>
        </div>
        <table class="table table-bordered table-hover">
            <thead>
                <tr class="th-style">
                    <th style="text-align:center;">@*<input type="checkbox" id="checkAll">*@<span id="delete" style="cursor:pointer; color:#3c8dbc;">Xóa</span></th>
                    <th>Loại chi phí</th>
                    <th>Số tiền</th>
                    <th>Ngày áp dụng</th>
                    <th>Năm học</th>
                    <th>Ghi chú</th>
                </tr>
            </thead>
            <tbody>
                @{
                    if (Model.danhSachDMHocPhi.Count > 0)
                    {
                        // int j = 0;
                        foreach (var i in Model.danhSachDMHocPhi)
                        {
                            // j++;
                            <tr>
                                <td style="text-align:center;"><input type="checkbox" class="checkBox" value="@i.maDMHP" style="transform: scale(1.5);" /></td>
                                <td>
                                    @Html.DisplayFor(m => i.tenLoaiChiPhi)
                                    <p>
                                        <a href="/Manager/DMHocPhi/ChucNang?type=Edit&maDMHP=@i.maDMHP&maNhomLop=@i.maNhomLop" class="lnkEdit">Chỉnh sửa</a>|
                                    </p>
                                </td>
                                <td> @Html.DisplayFor(m => i.soTien)</td>
                                <td> @Html.DisplayFor(m => i.ngayApDung)</td>
                                <td> @Html.DisplayFor(m => i.namHoc)</td>
                                <td> @Html.DisplayFor(m => i.ghiChu)</td>
                            </tr>
                        }
                    }
                    else
                    {
                        <tr>
                            <td colspan="6"> <p style="text-align:center;">Không có bản ghi nào</p></td>
                        </tr>
                    }
                }
            </tbody>
        </table>
        @Html.ActionLink("<< Quay lại danh sách", "Index", "NhomLop")
    </div>
</section>
@section Scripts{
    <script>
        $(document).ready(function () {
            //xóa danh sách tin tức đã chọn trong ô checkbox
            //The pop() method removes the last element of an array, and returns that element.
            $("#checkAll").click(function () {
                $(".checkBox").prop('checked', $(this).prop('checked'));
            });

            $("#delete").click(function () {
                var selectedIDs = new Array();
                $('input:checkbox.checkBox').each(function () {
                    if ($(this).prop('checked')) {
                        selectedIDs.push($(this).val());
                    }
                });
                console.log(selectedIDs.length);
                //nếu không chọn cái nào mà nhấn click thì đưa ra thông báo
                if (selectedIDs.length == 0) {
                    alert("Không có bản ghi nào được chọn.");
                }
                else {
                    var answer = confirm("Bạn có chắc chắn xóa bản ghi đã chọn ?");
                    if (answer) {
                        $.ajax({
                            type: "POST",
                            url: '@(Url.Action("XoaDMHP", "DMHocPhi"))',
                            data: { dmIDs: selectedIDs },
                            dataType: "json",
                            success: function (data) {
                                alert(data);
                                location.reload();
                            },
                            error: function (error) {

                            }
                        });
                    }
                };/////
            });
        });
        //kết thúc xóa tin từ ô checkbox
    </script>
}

Areas/Manager/Views/DMHocPhi/Index.cshtml
@model TestDA.Areas.Manager.Models.ViewModel.DMHocPhiData

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Manager/Views/Shared/_AdminPartial.cshtml";
}

<section class="content-header">
    <h1>
        <i class="fa fa-building-o"></i>
        Định mức học phí
        <small></small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Trang chủ</a></li>
        <li class="active">Định mức học phí</li>
    </ol>
</section>
<section class="content">
    <!-- Main content -->
    <div class="container body-content">
        <div class="content-dichvuthem">
            <h2>Danh sách khoản định mức</h2>
            @using (Html.BeginForm("Index", "DMHocPhi", FormMethod.Get, new { @class = "form-inline", role = "search", id = "search-form", onsubmit = "return empty();" }))
            {
                @*@Html.AntiForgeryToken()*@
                if (@TempData["Success"] != null)
                {
                    <div class="add-sucess">
                        <script>
                            toastr.options = {
                                "closeButton": true,
                                "debug": false,
                                "newestOnTop": false,
                                "progressBar": false,
                                "positionClass": "toast-bottom-right",
                                "preventDuplicates": false,
                                "onclick": null,
                                "showDuration": "300",
                                "hideDuration": "1000",
                                "timeOut": "5000",
                                "extendedTimeOut": "1000",
                                "showEasing": "swing",
                                "hideEasing": "linear",
                                "showMethod": "fadeIn",
                                "hideMethod": "fadeOut"
                            };
                            toastr["success"]("@TempData["Success"]");
                        </script>
                    </div>
                }
                <div class="form-inline">
                    <div class="">
                        @*tìm kiếm*@
                        <div class="form-group">
                            <label class="choice-type btn btn-default disabled">Tìm kiếm thông tin <i class="fa fa-angle-double-right" aria-hidden="true"></i></label>
                        </div>
                        <div class="form-group">
                            @Html.DropDownList("namHoc", ViewBag.namHoc as SelectList, "--Chọn năm học-- ", new { @class = "form-control", @id = "name-group", @style = "width: 200px;" })
                        </div>
                        <div class="form-group">
                            <button type="submit" class="btn btn-primary hidden-xs"><i class="fa fa-search">Tìm kiếm</i></button>
                        </div>
                    </div>
                    <div class="clearfix">  </div>
                    @Html.Raw("<span class='pull-right'> Tổng số bản ghi là: " + Model.danhSachDMHocPhi.Count().ToString() + "</span>")

                </div>
            }
            @*thêm mới bản ghi*@
            <div class="form-inline" style=" margin: 10px 0;">
                <div class="form-group">
                    <a href="/Manager/DMHocPhi/ChucNang?type=Insert" class="btn btn-primary hidden-xs"><i class="glyphicon glyphicon-plus"></i>Thêm mới bản ghi</a>
                </div>
            </div>
        </div>
        @*kết thúc form tìm kiếm*@
        <div id="dsnhaCC">
            <table class="table table-bordered table-hover">
                <thead>
                    <tr class="th-style">
                        <th>STT</th>
                        <th>Loại chi phí</th>
                        <th>Số tiền</th>
                        <th>Ngày áp dụng</th>
                        <th>Hình thức</th>
                        <th>Năm học</th>
                        <th>Chức năng</th>
                    </tr>
                </thead>
                <tbody>
                    @{
                        if (Model.danhSachDMHocPhi.Count > 0)
                        {
                            int j = 0;
                            foreach (var i in Model.danhSachDMHocPhi)
                            {
                                j++;
                                <tr>
                                    <td>@j.ToString()</td>
                                    <td>
                                        @Html.DisplayFor(m => i.tenLoaiChiPhi)
                                    </td>
                                    <td>@Html.DisplayFor(m => i.soTien)</td>
                                    <td>@Html.DisplayFor(m => i.ngayApDung)</td>
                                    <td>
                                        @if (i.loaiApDung == "1")
                                        {
                                            <span>Đóng theo tháng</span>
                                        }
                                        else
                                        {
                                            <span>Đóng theo năm</span>
                                        }
                                    </td>
                                    <td>@Html.DisplayFor(m => i.namHoc)</td>
                                    <td>
                                        <a href="/Manager/DMHocPhi/ChucNang?type=Edit&maDMHP=@i.maDMHP" class="lnkEdit" data-value="@i.maDMHP" id="dmHP_@i.maDMHP">Sửa | </a>
                                        <a href="javascript:void(0)" class="lnkDelete" data-value="@i.maDMHP" id="groupDV_@i.maDMHP">Xóa</a>
                                    </td>
                                </tr>
                            }
                        }
                        else
                        {
                            <tr>
                                <td colspan="7"> <p style="text-align:center;font-weight:bold;">Không có bản ghi nào</p></td>
                            </tr>
                        }
                    }
                </tbody>
            </table>
        </div>
    </div>
</section>
@section Scripts{
    <script>
        $(function () {
            //xóa một bản ghi
            $("a.lnkDelete").on("click", function () {
                var id = $(this).data('value');//lấy giá trị id của bản ghi
                console.log(id);
                var $tr = $(this).closest('tr');
                var answer = confirm("Bạn có chắc chắn xóa bản ghi này . Tiếp tục?");
                if (answer)
                    $.ajax({
                        type: "POST",
                        url: "@(Url.Action("XoaDMHocPhi", "DMHocPhi"))",
                        data: { maDMHP: id },
                        success: function (data) {
                            if (data == 0) {
                                $tr.css("background-color", "#ec645e");
                                location.reload();
                                //hiển thị thông báo ra màn hình
                                toastr.options = {
                                    "closeButton": true,
                                    "debug": false,
                                    "newestOnTop": false,
                                    "progressBar": false,
                                    "positionClass": "toast-bottom-right",
                                    "preventDuplicates": false,
                                    "onclick": null,
                                    "showDuration": "300",
                                    "hideDuration": "1000",
                                    "timeOut": "5000",
                                    "extendedTimeOut": "1000",
                                    "showEasing": "swing",
                                    "hideEasing": "linear",
                                    "showMethod": "fadeIn",
                                    "hideMethod": "fadeOut"
                                };

                                toastr["success"]("Xóa bản ghi thành công");

                            } else {
                                alert("Đã xảy ra lỗi!");
                            }
                        },
                        error: function (error) {
                        }
                    });
                return false;
            });
        })//Xóa một bản ghi
        function empty() {
            var x = $('#search-box').val();
            if (x == " " || x == null) {
                var url = window.location.pathname;
                window.location(url);
                // return false;
            }
        }
    </script>
}